version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'paradigma'
      MYSQL_PASSWORD: 'paradigma'
      MYSQL_ROOT_PASSWORD: 'paradigma'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - database:/var/lib/mysql

volumes:
  database: